const { UEGraphExecutor } = require('../js/ue_engine.js');
const nlp = require('compromise');

// The 'Golden JSON' generated by compiling the Teacher's Precision Agriculture Marking Scheme
const goldenJSON = {
  "questions": {
    "Q6_A_i": { "title": "Variable rate tech", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "management approach", "weight": 0.25 }, { "concept": "addressing spatial variability", "weight": 0.25, "synonyms": ["deals with in field variabilities"] } ] },
    "Q6_A_ii": { "title": "VRT Components", "type": "logic", "total_marks": 1.5, "nodes": [ { "concept": "Sensors", "weight": 0.5 }, { "concept": "Controllers", "weight": 0.5 }, { "concept": "Actuators", "weight": 0.5 } ] },
    "Q6_A_iii": { "title": "Land variabilities", "type": "logic", "total_marks": 2.0, "nodes": [ { "concept": "Soil fertility", "weight": 0.4, "synonyms": ["soil nutrients"] }, { "concept": "Soil organic matter", "weight": 0.4 }, { "concept": "Soil texture", "weight": 0.4 }, { "concept": "Soil moisture", "weight": 0.4 }, { "concept": "Soil colour", "weight": 0.4 } ] },
    "Q6_A_iv": { "title": "Sensors", "type": "logic", "total_marks": 2.5, "nodes": [ { "concept": "Pressure sensor", "weight": 0.5 }, { "concept": "Flow sensor", "weight": 0.5, "synonyms": ["grain flow"] }, { "concept": "Moisture sensor", "weight": 0.5, "synonyms": ["grain moisture"] }, { "concept": "Speed sensor", "weight": 0.5 }, { "concept": "Grain loss sensor", "weight": 0.5 } ] },
    "Q6_B_i": { "title": "Percentage Loss", "type": "math", "total_marks": 5.5, "expected_answer": 1.8, "tolerance": 0.05 },
    "Q6_B_ii": { "title": "Maize Revenue", "type": "math", "total_marks": 8, "expected_answer": 9333310, "tolerance": 0.05 },

    "Q3_A_i": { "title": "Precision Agriculture", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "application of technology", "weight": 0.25 }, { "concept": "increase productivity", "weight": 0.25 } ] },
    "Q3_A_ii": { "title": "Challenges", "type": "logic", "total_marks": 4, "nodes": [ { "concept": "Perception and cultural beliefs", "weight": 0.5 }, { "concept": "Farm fragmentation", "weight": 0.5 }, { "concept": "High initial cost", "weight": 0.5 }, { "concept": "network systems", "weight": 0.5, "synonyms": ["network systems and bandwidth"] }, { "concept": "requires knowledge", "weight": 0.5, "synonyms": ["lack of technical experts"] }, { "concept": "skilled Labors", "weight": 0.5 }, { "concept": "Poor electrical systems", "weight": 0.5 } ] },
    "Q3_B": { "title": "Adoption Reasons", "type": "logic", "total_marks": 10, "nodes": [ { "concept": "manage large farms", "weight": 2.0, "synonyms": ["easy/reliable way to manage"] }, { "concept": "Reduce cost", "weight": 2.0 }, { "concept": "Increase yield", "weight": 2.0, "synonyms": ["increase productivity"] }, { "concept": "Increase Efficiency", "weight": 2.0 }, { "concept": "Optimize scarce resources", "weight": 2.0 } ] },

    "Q3_A_iii": { "title": "Building Blocks", "type": "logic", "total_marks": 5.5, "nodes": [ { "concept": "Information", "weight": 1.83, "synonyms": ["database"] }, { "concept": "Technology", "weight": 1.83 }, { "concept": "Management", "weight": 1.83 } ] },

    "Q2_A_i": { "title": "Remote Sensing", "type": "logic", "total_marks": 1.0, "nodes": [ { "concept": "control an object", "weight": 0.5, "synonyms": ["collecting information"] }, { "concept": "without physical contact", "weight": 0.5 } ] },
    "Q2_A_ii": { "title": "Environment Sensors", "type": "logic", "total_marks": 2.5, "nodes": [ { "concept": "Soil moisture", "weight": 0.5, "synonyms": ["moisture content"] }, { "concept": "Soil pH", "weight": 0.5 }, { "concept": "Nutrient sensor", "weight": 0.5 }, { "concept": "Temperature sensor", "weight": 0.5 }, { "concept": "Relative humidity", "weight": 0.5 } ] },
    "Q2_A_iii": { "title": "Steps to apply", "type": "logic", "total_marks": 3.5, "nodes": [ { "concept": "Collection", "weight": 0.5 }, { "concept": "Pre-processing", "weight": 0.5 }, { "concept": "Image analysis", "weight": 0.5 }, { "concept": "Validation", "weight": 0.5, "synonyms": ["verification"] }, { "concept": "Incorporation", "weight": 0.5 }, { "concept": "Identification", "weight": 0.5 }, { "concept": "Action", "weight": 0.5 } ] },

    "Q2_B_i": { "title": "Types of RS", "type": "logic", "total_marks": 5.5, "nodes": [ { "concept": "Active", "weight": 2.75, "synonyms": ["emits its own signals"] }, { "concept": "Passive", "weight": 2.75, "synonyms": ["uses already reflected radiations"] } ] },
    "Q2_B_ii": { "title": "Acquire image", "type": "logic", "total_marks": 7.5, "nodes": [ { "concept": "Via Sensor", "weight": 2.5, "synonyms": ["Frame-by-frame"] }, { "concept": "Whisk broom", "weight": 2.5 }, { "concept": "Array", "weight": 2.5, "synonyms": ["line method"] } ] },

    "Q5_A_i": { "title": "Define GPS", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "determine accurate location", "weight": 0.25 }, { "concept": "satellite-based", "weight": 0.25 } ] },
    "Q5_A_ii": { "title": "GNSS in PA", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "GPS", "weight": 0.5 } ] },
    "Q5_C": { "title": "DGPS Principles Diagram", "type": "logic", "total_marks": 10, "nodes": [ { "concept": "Rover", "weight": 2.0 }, { "concept": "Base receiver", "weight": 2.0 }, { "concept": "Satellites transmit signals", "weight": 2.0 }, { "concept": "differential radiations", "weight": 2.0 }, { "concept": "corrects location", "weight": 2.0 } ] },
    "Q5_B": { "title": "Types of DGPS", "type": "logic", "total_marks": 9, "nodes": [ { "concept": "SBAS", "weight": 3.0 }, { "concept": "RTCM", "weight": 3.0 }, { "concept": "RTK", "weight": 3.0 } ] },

    "Q1_A_i": { "title": "Field Invariabilities", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "conditions of crop, soil", "weight": 0.25 }, { "concept": "does not change", "weight": 0.25 } ] },
    "Q1_A_ii": { "title": "Beneficial Nutrients", "type": "logic", "total_marks": 0.5, "fatal_contradictions": ["Are essential", "IS_ESSENTIAL"], "nodes": [ { "concept": "not essential", "weight": 0.5, "synonyms": ["do not meet criteria of essentiality"] } ] },
    "Q1_A_iii": { "title": "Wicking system", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "soilless", "weight": 0.25 }, { "concept": "capillarity action", "weight": 0.25 } ] },
    "Q1_A_iv": { "title": "Aeroponics", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "suspended on air", "weight": 0.25 }, { "concept": "misting roots", "weight": 0.25 } ] },
    "Q1_A_v": { "title": "Ebb and Flow", "type": "logic", "total_marks": 0.5, "nodes": [ { "concept": "flooded", "weight": 0.25 }, { "concept": "drained", "weight": 0.25 } ] },

    "Q1_B_i": { "title": "PA vs PT", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "increase productivity", "weight": 0.5 }, { "concept": "use of sensors and satellites", "weight": 0.5 } ] },
    "Q1_B_ii": { "title": "Tech vs Science", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "application of scientific knowledge", "weight": 0.5 }, { "concept": "exploring of new knowledge", "weight": 0.5 } ] },
    "Q1_B_iii": { "title": "GPS vs GIS", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "determine position", "weight": 0.5 }, { "concept": "analyzing geographical data", "weight": 0.5 } ] },
    "Q1_B_iv": { "title": "PA vs PF", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "crops and animals", "weight": 0.5 }, { "concept": "crop productivity only", "weight": 0.5, "synonyms": ["increase productivity"] } ] },
    "Q1_B_v": { "title": "Wicking vs Hydroponic", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "capillarity", "weight": 0.5 }, { "concept": "working water", "weight": 0.5 } ] },
    "Q1_B_vi": { "title": "RTK vs DGPS", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "RTCM protocol", "weight": 0.5 }, { "concept": "differential radiations", "weight": 0.5 } ] },
    "Q1_B_vii": { "title": "Hydroponics vs Aquaponics", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "working water", "weight": 0.5 }, { "concept": "symbiotic way", "weight": 0.5 } ] },
    "Q1_B_viii": { "title": "GPS vs DGPS", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "one receiver", "weight": 0.5 }, { "concept": "two receivers", "weight": 0.5 } ] },
    "Q1_B_ix": { "title": "NCV vs Luxury", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "deficient of nutrient", "weight": 0.5 }, { "concept": "excess uptaking", "weight": 0.5 } ] },
    "Q1_B_x": { "title": "Hidden hunger vs Optimal", "type": "logic", "total_marks": 1, "nodes": [ { "concept": "doesn't show signs", "weight": 0.5 }, { "concept": "available for production", "weight": 0.5 } ] },
    "Q1_C": { "title": "Farming activities", "type": "logic", "total_marks": 7.5, "nodes": [ { "concept": "Tillage", "weight": 1.5 }, { "concept": "Fertilizer Application", "weight": 1.5 }, { "concept": "Spraying", "weight": 1.5 }, { "concept": "Crop Scouting", "weight": 1.5 }, { "concept": "Harvesting", "weight": 1.5 } ] }
  }
};

// Student's scattered answers properly mapped by Semantic Extraction into question IDs
const studentAnswers = {
    "Q6_A_i": "Variable rate Technology is the only technology which deals with in field variabilities like Soil fertility, organic matter content and Soil Organic matters.",
    "Q6_A_ii": "a) Sensors b) Controllers c) Actuators",
    "Q6_A_iii": "a) Soil fertility b) Soil Organic matters content c) Soil texture d) Soil Moisture Content e) Soil color",
    "Q6_A_iv": "a) Pressure Sensors b) Grain flow c) Grain moisture d) Speed Sensors e) Grain loss sensors",
    "Q6_B_i": "Yield Remained = 20Mg - 2Mg = 18Mg. Now: 20 Mg = 18%, 18 Mg = y. y = (18 * 18%) / 20 Mg. y = 16.2%. 18% - 16.2% = 1.8%",
    "Q6_B_ii": "x = (12% * 18 Mg) / 16.2. x = 13.33 Mg will be sold. Number of bags = 13333 kg / 100 kg = 133.33 bags. Price to pay = 133.33 bags * 70,000 Tsh. Price to pay = 9,333,333.33 Tsh.",
    "Q3_A_i": "Precision Agriculture is the application of technology within agriculture to increase productivity while decreasing cost of production.",
    "Q3_A_ii": "a) Perception and cultural beliefs b) Farm fragmentation c) High initial cost d) Low network systems e) requires knowledge f) requires skilled Labors g) Lack of technical experts h) Poor electrical systems",
    "Q3_B": "i) Easy / Reliable way to manage large farms ii) Reduce cost iii) Increase yield Productivity iv) Increase Efficiency v) Optimize the Use of scarce resources",
    "Q3_A_iii": "Seed: In precision Agriculture seed sowing to required depth... Fertilizer: Application of fertilizer... Pesticides: Precision Agriculture plays great role...",
    "Q2_A_i": "Remote Sensing is a technique used to control an object or area of interest without being physically contact with it.",
    "Q2_A_ii": "a) Grain flow sensors b) Grain loss sensors c) Speed sensors d) Header Position sensors e) Moisture content sensors",
    "Q2_A_iii": "a) Collection b) Pre-processing c) Image analysis d) Ground validation / Verification e) Incorporation f) Identification g) Action",
    "Q2_B_i": "a) Active remote sensing - emits its own signals b) Passive Remote Sensing - uses already reflected radiations",
    "Q2_B_ii": "a) Via Sensor - Frame-by-frame b) Whisk broom sensor c) Array (line) method",
    "Q5_A_i": "Global Positioning System is the technology which used to determine accurate location",
    "Q5_A_ii": "GPS (USA)",
    "Q5_C": "Satellites transmit signals to both two receivers of DGPS (Rover and Base receiver)... sending differential radiations to the rover. DGPS corrects the location exactly.",
    "Q5_B": "SBAS, RTCM, RTK",
    "Q1_A_i": "Field invariabilities - Are those conditions of crop, soil and environment which does not change",
    "Q1_A_ii": "Are essential or important nutrients which are required for growth and production. Examples: Sodium (Na)",
    "Q1_A_iii": "nutrient solution is moving from tank to tray holding plants, through wicks and by capillarity action",
    "Q1_A_iv": "misting roots of a plant suspended on air",
    "Q1_A_v": "plants are flooded with nutrient for few hours and then water are drained",
    "Q1_B_i": "Precision Agriculture is application of technology to increase productivity... WHILE Precision Technology is the technology which employ use of sensors and satellites.",
    "Q1_B_ii": "Technology is an application of scientific knowledge... WHILE Science is exploring of new knowledge",
    "Q1_B_iii": "GPS: technology used to determine position... WHILE GIS: method of identifying, collecting, storing and analyzing geographical data.",
    "Q1_B_iv": "Precision Agriculture - application of technology to increase productivity of both crops and animals... WHILE Precision Farming - application of technology principles of farming to increase productivity.",
    "Q1_B_v": "Wicking system - nutrient moves through wick by capillarity... WHILE Hydroponic System - application of nutrient solution by working water",
    "Q1_B_vi": "Real Time Kinematics - part of DGPS which uses RTCM protocol... WHILE DGPS - technology providing accurate position through differential radiations",
    "Q1_B_vii": "Hydroponics - soilless farming cooperating working water supplying nutrients... WHILE Aquaponics - growing of aquatic animals and plants in a symbiotic way.",
    "Q1_B_viii": "GPS: Has one receiver | DGPS: Has two receivers.",
    "Q1_B_ix": "Nutrient Critical value - point below which a plant will be deficient of nutrient... WHILE Luxury Consumption - excess uptaking",
    "Q1_B_x": "Plants Nutrient optimal hunger - point at which a plant requires nutrients but doesn't show signs... WHILE Optimal Soil Nutrient Level - point at which nutrients are available for production",
    "Q1_C": "a) Tillage b) Fertilizer Application c) Spraying d) Crop Scouting e) Harvesting"
};

console.log("=========================================================================");
console.log("🏫 PLAYBOOK UE ENGINE - FINAL EXECUTION DUMP");
console.log("STUDENT REGISTRATION: 2018-04-12551");
console.log("=========================================================================\n");

const executor = new UEGraphExecutor(goldenJSON);
executor.nlp = nlp;
const result = executor.execute(studentAnswers);

console.log(`🏆 FINAL CALCULATED SCORE: ${result.totalScore} Marks\n`);

for (const [qId, data] of Object.entries(result.breakdown)) {
    console.log(`▶ Question: ${qId}`);
    console.log(`   Marks Awarded: ${data.score} / ${data.max_marks}`);
    console.log(`   Justification:\n   ${data.justification.replace(/\n/g, '\n   ')}`);
    console.log("---------------------------------------------------------");
}
